# Generated by Django 4.0 on 2023-02-09 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Active_Player_List',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_id', models.CharField(default='', max_length=100)),
                ('last_name', models.CharField(default='', max_length=100)),
                ('other_name', models.CharField(default='', max_length=100)),
                ('mobile_number', models.CharField(default='', max_length=100)),
                ('promo_request', models.CharField(default='', max_length=100)),
                ('date_created', models.CharField(default='', max_length=100)),
            ],
            options={
                'db_table': 'active_player_list',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Actual_Ticket_Information',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_name', models.CharField(default='', max_length=100)),
                ('mobile_number', models.CharField(default='', max_length=100)),
                ('price', models.CharField(default='', max_length=300)),
                ('date_created', models.CharField(default='', max_length=100)),
            ],
            options={
                'db_table': 'actual_ticket_info',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Mobile_Number_Directory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile_number', models.CharField(default='', max_length=12)),
                ('source', models.CharField(blank=True, default='', max_length=200, null=True)),
            ],
            options={
                'db_table': 'mobile_number_directory',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Sales_Transactions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_date', models.CharField(default='', max_length=100)),
                ('transaction_id', models.CharField(default='', max_length=100)),
                ('mobile_number', models.CharField(default='', max_length=100)),
                ('player_name', models.CharField(default='', max_length=100)),
                ('network', models.CharField(default='', max_length=100)),
                ('number_of_tickets', models.CharField(default='', max_length=100)),
                ('amount', models.CharField(default='', max_length=100)),
            ],
            options={
                'db_table': 'sales_transactions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Active_Player_File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='ActivePlayerList')),
            ],
        ),
        migrations.CreateModel(
            name='Actual_Ticket_Info_File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='ActualTicketInfo')),
            ],
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='files')),
            ],
        ),
        migrations.CreateModel(
            name='Sales_Transactions_File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='SalesTransactions')),
            ],
        ),
        migrations.CreateModel(
            name='Winning_Tickets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('draw_id', models.CharField(default='', max_length=100)),
                ('draw_name', models.CharField(default='', max_length=100)),
                ('player_name', models.CharField(default='', max_length=100)),
                ('mobile_number', models.CharField(default='', max_length=100)),
                ('ticket_number', models.CharField(default='', max_length=100)),
                ('price_amount', models.CharField(default='', max_length=100)),
                ('price_category', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Winning_Tickets_File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='WinningTickets')),
            ],
        ),
    ]
