# Generated by Django 4.0 on 2023-01-21 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lottery', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mobile_number_directory',
            options={'managed': False},
        ),
    ]
