# Generated by Django 4.0 on 2023-01-17 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lottery', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mobile_number_directory',
            name='id',
            field=models.CharField(max_length=100),
        ),
    ]
