# Generated by Django 4.0 on 2023-01-18 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lottery', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='active_player_list',
            name='promo_request',
            field=models.CharField(default='', max_length=100),
        ),
    ]
