# Generated by Django 4.0 on 2023-01-17 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lottery', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mobile_number_directory',
            name='mobile_number',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
