# Generated by Django 4.0 on 2023-01-21 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lottery', '0002_alter_mobile_number_directory_options'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='mobile_number_directory',
            table='Mobile_Number_Directory',
        ),
    ]
