# Generated by Django 4.0 on 2023-02-10 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lottery', '0002_remove_winning_tickets_id_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='winning_tickets',
            options={'managed': False},
        ),
    ]
