# Generated by Django 4.0 on 2023-01-21 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lottery', '0003_alter_mobile_number_directory_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='mobile_number_directory',
            table='mobile_number_directory',
        ),
    ]
