# Generated by Django 4.0 on 2023-01-29 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lottery', '0006_alter_file_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='Active_Player_File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='ActivePlayerList')),
            ],
        ),
        migrations.CreateModel(
            name='Actual_Ticket_Info_File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='ActualTicketInfo')),
            ],
        ),
        migrations.CreateModel(
            name='Sales_Transactions_File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='SalesTransactions')),
            ],
        ),
        migrations.CreateModel(
            name='Winning_Tickets_File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='WinningTickets')),
            ],
        ),
        migrations.AlterModelOptions(
            name='active_player_list',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='actual_ticket_information',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='sales_transactions',
            options={'managed': False},
        ),
    ]
